stages:
  - testing
  - deploy
  - pages

.python_base: &python_base
  tags:
    - docker
  image: python:3.7
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
      - .venv
    key: "$CI_PROJECT_ID"
  before_script:
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@mad-srv.informatik.uni-erlangen.de" > ~/.git-credentials
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install

test:
  stage: testing
  <<: *python_base
  script:
    - poetry run pytest

lint-prospector:
  stage: testing
  <<: *python_base
  script:
    - poetry run prospector

lint-black:
  stage: testing
  <<: *python_base
  script:
    - poetry run black . --check
