strictness: veryhigh
doc-warnings: true

ignore-paths:
  - docs
  - tests

pep8:
  options:
    max-line-length: 120
  disable:
    - E127
    - W391

pep257:
  options:
    convention: numpy
  disable:
    - D404
    - D100  # Missing docstring in public module, handled by pylint
    - D101  # Missing docstring in public class, handled by pylint
    - D102  # Missing docstring in public method, handled by pylint
    - D104  # Missing docstring in public package, handled by pylint


pylint:
  options:
    max-line-length: 120
  disable:
    - too-many-ancestors
    - too-few-public-methods
    - invalid-unary-operand-type
