[tool.poetry]
name = "gaitmap"
version = "0.1.0"
description = "The Gait and Movement Analysis Package - Your definite guide to reliable IMU based human movement analysis."
authors = [
    "Arne Küderle <arne.kuederle@fau.de>",
    "Martin Ullrich <martin.ullrich@fau.de>",
    "Nils Roth <nils.roth@fau.de>",
    "Malte Ollenschläger <Malte.Ollenschlaeger@fau.de>",
    "Alzhraa Ahmed <alzhraa.ahmed@fau.de>",
    "Felix Kluge <felix.kluge@fau.de>"
]

[tool.poetry.dependencies]
python = "^3.7"
tslearn = "^0.3.0"
pandas = "^1.0.3"
scipy = "^1.4.1"
typing_extensions = "^3.7.4"
numba = "^0.49.0"
numpy = "^1.18.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8.1"
prospector = "^1.2.0"
black = "^19.10b0"
sphinx = "^3.0.1"
numpydoc = "^0.9.2"
sphinx_gallery = "^0.5.0"
sphinx_issues = "^1.2.0"
recommonmark = "^0.6.0"
coverage = "^4.5.4"
sphinx_bootstrap_theme = "^0.7.1"
doit = "^0.32.0"
ipykernel = "^5.2.0"
IPython = "^7.13.0"
ipympl = "^0.5.6"

[tool.black]
line-length = 120
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | docs
    | build
    | dist
    | \.virtual_documents
  )/
)
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

