[tool.poetry]
name = "gaitmap"
version = "0.1.0"
description = "The Gait and Movement Analysis Package - Your definite guide to reliable IMU based human movement analysis."
authors = ["Arne Küderle <arne.kuederle@fau.de>"]

[tool.poetry.dependencies]
python = "^3.7"
black = "^19.10b0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8.1"
prospector = "^1.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 120
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | docs
    | build
    | dist
  )/
)
'''